# Команда для билда - docker build . -f Dockerfile_to_clear_linux -t my_linux_to_python
# Команда для запуска - docker run -it -p 8080:80 id_images
# Если вдруг нет доступа к серверу - вероятная причина ip в файле uwsgi_config.ini
#   вощможно диреватива http не совпадает с ip адресом контейенра

FROM debian

WORKDIR /app

# Обновление системы
RUN apt update
RUN apt upgrade

# Устанвка зависимостей
RUN apt install build-essential zlib1g-dev  \
    libncurses5-dev libgdbm-dev libnss3-dev  \
    libssl-dev libreadline-dev libffi-dev  \
    libsqlite3-dev wget libbz2-dev pkg-config -y

# Стягивание и распаковка python
RUN wget https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tgz
RUN tar -xf Python-3.11.*.tgz

# Проверка доступности зависимостей
RUN Python-3.11.5/configure --enable-optimizations

# Сборка и установка python
RUN make -j 2
RUN make altinstall

# Уставновка необходимых расширений
RUN apt install python3-pip -y

# Копирование проекта
COPY . .

# Установка зависимостей
RUN pip install --upgrade pip --break-system-packages
RUN pip install -r requirements.txt --break-system-packages
RUN pip install uwsgi --break-system-packages

# Запускаем сервер
CMD ["uwsgi", "uwsgi_config.ini"]
