# Команда для билда - docker build . -f Dockerfile_for_ubuntu -t my_ubuntu_to_python
# Команда для запуска -
#   docker run --name my_server_ubuntu_container -it -p 8080:80 -v C:\ArhitectFiles\PythonProjects\Tennis_ball_scoreboard:/app my_ubuntu_to_python

FROM ubuntu

WORKDIR /app

COPY . .

RUN apt update
RUN apt upgrade -y

RUN apt install python3 -y
RUN apt install pip -y

RUN pip install --upgrade pip
RUN pip install uwsgi
RUN pip install -r requirements.txt

CMD ["uwsgi", "uwsgi_config.ini"]
