"""”add_column_Score_in_table_Match

Revision ID: 0f6d8c0676fe
Revises: d98fe4e6fe59
Create Date: 2023-10-08 20:58:10.539870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6d8c0676fe'
down_revision = 'd98fe4e6fe59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('Score', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Match', 'Score')
    # ### end Alembic commands ###
