"""”update_len_column_score

Revision ID: 6a6f5dcb66b7
Revises: e69d89b7b17b
Create Date: 2023-10-09 00:21:46.527041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a6f5dcb66b7'
down_revision = 'e69d89b7b17b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Match', 'Score',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Match', 'Score',
               existing_type=sa.VARCHAR(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
