"""fields_changed_foreign_keys

Revision ID: a9bf2235e4df
Revises: 7425cbda03d3
Create Date: 2023-06-30 22:40:11.419229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9bf2235e4df'
down_revision = '7425cbda03d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
