"""create unique index in table Player

Revision ID: c70ea37ff3d9
Revises: a9bf2235e4df
Create Date: 2023-07-14 17:13:46.920772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70ea37ff3d9'
down_revision = 'a9bf2235e4df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Players_Name', table_name='Player')
    op.create_index(op.f('ix_Players_Name'), 'Player', ['Name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Players_Name'), table_name='Player')
    op.create_index('ix_Players_Name', 'Player', ['Name'], unique=False)
    # ### end Alembic commands ###
