"""”MatchWinnerIsNullible”

Revision ID: d98fe4e6fe59
Revises: bab32c998b77
Create Date: 2023-10-02 01:11:13.469802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd98fe4e6fe59'
down_revision = 'bab32c998b77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Match', 'Winner',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Match', 'Winner',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
