"""”len_column_score

Revision ID: e69d89b7b17b
Revises: 0f6d8c0676fe
Create Date: 2023-10-09 00:19:49.631879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e69d89b7b17b'
down_revision = '0f6d8c0676fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Match', 'Score',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Match', 'Score',
               existing_type=sa.VARCHAR(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
