"""head

Revision ID: eb011c6a3385
Revises: 14e2ca6f5202
Create Date: 2023-06-09 01:18:12.260430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb011c6a3385'
down_revision = '14e2ca6f5202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
